language: node_js
node_js:
  - "4.0"
  
before_script:
  - mkdir -p $HOME/bin
  - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url samples.testspace.com
  - testspace -v
  - npm install
  
script: 
  - make lint test 
  
# Requires TESTSPACE_TOKEN environment variable.   
after_script:
  - testspace checkstyle.xml [Tests]xunit.xml{test} coverage/cobertura-coverage.xml