name: Build
on:
  push:
  schedule:
    - cron:  '0 1 * * 0'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '6'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: samples
      - name: Install
        run: |
          npm install
      - name: Test
        run: |
          make lint test
      - name: Push
        run: |
          testspace checkstyle.xml [Tests]xunit.xml{test} coverage/cobertura-coverage.xml
        if: always()
